[Feat] 투표 도메인 테스트 코드 개발
four-uncles/saramara-community-server pull request #150
Opened 2024-02-28 08:50 UTC by IToriginal

## 🤔 Motivation
- 투표 관련 단위테스트와 통합테스트, 슬라이스 테스트를 DCI 패턴으로 생성/리팩토링하게 되었습니다.
- 투표 조회 API 관련 회원, 비회원 권한은 상관하지 않고 API를 사용할 수 있도록 테스트가 수정되었습니다.
- 테스트 작성에 필요한 예외 처리가 추가 되었습니다. 

<br>

## 💡 Key Changes
### 1. Unit Test

<img width="547" alt="image" src="https://github.com/four-uncles/saramara-community-server/assets/117193889/6b8eecb0-a3ad-4cf2-ae1e-931ff9d7f488">

시나리오의 변경에 따라 불필요한 분기를 삭제하고 시나리오의 내용을 보다 상세하게 수정하였습니다.

### 2. Integration Test

<img width="531" alt="image" src="https://github.com/four-uncles/saramara-community-server/assets/117193889/a1854d95-4970-4a2d-8ee4-245d38921ca3">

투표 조회 API 관련 이슈를 적용하여 시나리오를 수정하고, 사용자 측면에서 와닿는 시나리오로 개선하였습니다.
슬랙을 활용한 @langoustinee 님과의 시나리오 토의를 통해서 아래의 사유로 비회원에 대한 예외처리는 생성에서 한번만 처리하도록 하였습니다.
> @langoustinee : 예외 케이스가 성립이 안되는 것들이 많아서 억지로 넣을 필요가 없다고 생각이 되요. 
> @IToriginal : 저도 비회원에 대해서는 좀 억지로 넣는 것 같다는 생각을 했는데, 불필요한게 맞을지가 의문이더라구요. 

**노션을 통해 설계된 시나리오 중 수정된 시나리오**
투표를 조회할 경우 (회원, 비회원에 관계 없이 통계를 조회할 수 있으므로, 아래와 같이 시나리오 변경)
- [BEFORE] `[Green] 본인의 투표 여부를 알 수 있다.`
- [AFTER] `[Green] 누구나 투표 현황을 알 수 있다.`

### 3. 예외 처리 구문 추가
한 회원은 한 번의 투표만 가능하기 때문에 게시글(`boardId`)와 회원(`memberId`)을 통해 투표가 이루어진 데이터가 존재하는 경우,
Spring Data JPA를 통해 `Optional` 타입의 `findByMemberIdAndBoardId` 메서드로 투표 객체를 찾고, 
이미 존재하는 데이터가 있다면, HTTP 상태 코드 `409` CONFILICT(리소스 충돌) 예외를 발생시키는 검증 로직을 추가하였습니다.

**추가된 테스트 시나리오**
- `[Red] 중복 투표는 할 수 없다.`

### 4. Slice Test

<img width="546" alt="image" src="https://github.com/four-uncles/saramara-community-server/assets/117193889/9467776f-6551-4cd9-9d6b-e3071442f456">

투표 조회 API 관련 이슈를 적용하여 시나리오를 수정하였습니다.

<br>

## 👨‍👨‍👧‍👦 To Reviewers
- @langoustinee
- 위의 내용에 대한 피드백 부탁드립니다.
- 추가적으로 개선할 수 있는 부분이나 주의해야 할 사항이 있다면 알려주시면 감사하겠습니다.

#131 
close: #142

2024-02-28 11:03 UTC, IToriginal commented
@langoustinee 투표 도메인에 변경된 슬라이스 테스트 시나리오를 적용할 예정입니다. 
슬라이스 테스트 관련 리뷰는 해당 작업이 PR에 추가되고 확인 부탁드리겠습니다 🔨

2024-03-02 06:23 UTC, IToriginal commented
@langoustinee 투표 도메인 슬라이스 테스트 시나리오를 추가하고, 투표 상태를 검증하고 응답하는 로직을 추가 하였습니다.

해당 내용은 PR content 수정을 완료하였으므로, 이를 확인해주시면 감사하겠습니다.✨

2024-03-02 11:25 UTC, langoustinee requested changes
어느덧 1차 개발 막바지 PR이 되어가네요.
투표 API 개발까지 수고 많으셨습니다. 간단하게 Request Changes 남겨두겠습니다.

2024-03-02 11:27 UTC, langoustinee commented on src/main/java/com/kakao/saramaracommunity/vote/controller/VoteController.java
> +            Principal principal
`Principal`과 관련해서 의견 주신 점은 감사합니다. `Principal`에 대한 요청 필드 이슈는 저도 함께 고민해보겠습니다. 

사용자 고유번호 노출을 줄이고자 여러 방면으로 고민해보고 적용해보며 많은 시도를 해볼 수 있을 것 같아요.

2024-03-02 11:28 UTC, langoustinee commented on src/main/java/com/kakao/saramaracommunity/vote/dto/business/response/VotesReadInBoardResponse.java
> +            Boolean isVoted,
`isVoted`라는 투표 진행 여부 필드를 함께 투표 조회 API의 응답으로 포함시킬지, 별도 API로 분리하여 단일 필드로 제공할지도 추후 함께 고민해봤으면 좋겠네요.

2024-03-02 11:47 UTC, langoustinee requested changes

2024-03-02 11:47 UTC, langoustinee commented on src/main/java/com/kakao/saramaracommunity/vote/service/VoteServiceImpl.java
> +    }
`getMemberInfo` 메서드는 디미터 법칙을 고려한다면, 객체 내부의 Getter에 의존하기보다는 객체에 메시지를 보내어 필요한 `memberId`를 알아오도록 하는 메서드를 추가로 개발할 수도 있겠네요!

```java
// Member
public class Member {
    // 생략
    public Long getMemberId() {
        return this.id;
    }
}

// VoteServiecImpl
private Long getMemberInfo(Principal principal) {
    return memberRepository.findMemberByEmail(principal.getName())
        .orElseThrow(() -> new MemberBusinessException(MEMBER_NOT_FOUND))
        .getMemberId();
}
```

요로코롬 말이죠! [링크](https://mangkyu.tistory.com/147)를 참조해보면 디미터 법칙과 관련해서 참고할 수 있을 겁니다..!

2024-03-02 11:47 UTC, langoustinee commented on src/test/java/com/kakao/saramaracommunity/vote/controller/VoteControllerTest.java
> +    @DisplayName("투표 여부 조회 시")
여기서는 `@DisplayName`이 아니라 `@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)`을 쓰도록 했으니 변경이 필요해 보여요! 

이 부분과 동일하게 작성된 아래 `@Nested` Class 모두 변경해주면 좋겠습니당!

2024-03-02 12:09 UTC, IToriginal commented on src/main/java/com/kakao/saramaracommunity/vote/controller/VoteController.java
> +            Principal principal
넵✨ 이전에 공유해주신 `@AuthenticationPrincipal` 를 사용하려 했는데, 아직 해당 어노테이션의 학습이 제대로 이뤄지지 않았고, `MemberRepository` 인터페이스에 구현되어진 `findMemberByEmail` JPA 를 활용한다면 `Principal` 만으로도 충분히 회원의 정보를 가져와 검증할 수 있을 것으로 판단하여 구현하였습니다!

해당 방법을 활용한다면 사용자 검증이 필요한 API에 활용될 수 있을 것 같습니다. 
다만 아직 취약점에 대해선 많은 생각을 하지 못하였고이를 고려하지 않은 상태로 적용이 된 점을 참고해주시고 이슈로 남겨놓은 [[Global/Refactor] 사용자 권한 검증을 위한 회원 정보 요청 필드 보안성 강화하기](https://github.com/orgs/four-uncles/projects/2?pane=issue&itemId=54649169) 작업을 진행할 때 이점을 포함해서 생각해보면 좋을 것 같습니다!

2024-03-02 12:26 UTC, IToriginal commented on src/main/java/com/kakao/saramaracommunity/vote/service/VoteServiceImpl.java
> +    }
링크 감사합니다. 저도 해당 디미터 법칙에 대해서 고민을 해봤는데, 말씀해주신 상황에서는 큰 차이를 못느끼겠더라구요..

물론 객체에 메시지를 보내서 필요한 데이터 값인 `memberId`를 가져오는 것을 이해하고 있는데, 아래와 같은 Getter와 메서드를 추가하는 것에 대한 차이가 있는가? 에서 항상 납득이 되지 않았습니다. 🥲

현재 상황에서도 `@Getter` 어노테이션을 클래스 레벨에서 사용중인데 디미터 법칙을 생각해서 `getMemberId()`라는 메서드를 추가로 구현해야할 필요가 있을지.. 죄송하게도 여전히... 이해되지 않고 있습니다.🥲

```java
// Member id Getter
public Long getId() {
      return this.id;
}
```

2024-03-02 12:30 UTC, IToriginal commented on src/test/java/com/kakao/saramaracommunity/vote/controller/VoteControllerTest.java
> +    @DisplayName("투표 여부 조회 시")
`@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)` 를 사용하도록 수정하겠습니다! 감사합니다.

2024-03-02 13:30 UTC, langoustinee commented on src/main/java/com/kakao/saramaracommunity/vote/service/VoteServiceImpl.java
> +    }
아, 제가 리뷰에서 언급한 디미터 법칙의 예시로 작성한 `getMemberId()`라는 메서드가 적절한 예시가 아님을 다시 전달드려요..!

객체 내부 구조에 의존하지 말라는 의미를 가지는 디미터 법칙을 준수하기 위해서는 위와 같이 .getId().xxx().xxx()와 같은 메서드 체이닝을 통해 내부 필드에 의존하게 되는 상황을 설명하려 하다가 예시에서 삼천포로 빠졌네요..! ㅋㅋ

제가 설명드린 예시는 무시하시고 추후 디미터 법칙을 어떻게 잘 반영할 수 있을까라는 생각만 가져가 주시면 될 것 같아요!
혼동을 드려 죄송합니다앗..

2024-03-02 13:31 UTC, langoustinee approved these changes
@DIsplayName 수정 내역 확인 했습니다!
차주에는 제가 회원쪽을 함께 건드릴 예정이라, 추후 회원 패키지 변경점 PR과 함께 돌아오겠습니다.

2024-03-02 13:41 UTC, merged